import { createFileRoute } from '@tanstack/react-router';
import Table from '../components/Table';

const RouteComponent = () => {
  // Generated by Supermaven
  const data = [
    { name: 'Banana', color: 'bg-yellow-500', score: 10 },
    { name: 'Orange', color: 'bg-orange-500', score: 20 },
    { name: 'Apple', color: 'bg-green-500', score: 30 },
    { name: 'Mango', color: 'bg-red-500', score: 40 },
    { name: 'Pineapple', color: 'bg-purple-500', score: 50 },
    { name: 'Grape', color: 'bg-blue-500', score: 60 },
    { name: 'Watermelon', color: 'bg-pink-500', score: 70 },
    { name: 'Strawberry', color: 'bg-teal-500', score: 80 },
    { name: 'Blueberry', color: 'bg-cyan-500', score: 90 },
    { name: 'Blackberry', color: 'bg-gray-500', score: 100 }
  ];

  const config = [{ label: 'Fruit' }, { label: 'Color' }, { label: 'Score' }];

  return <Table data={data} config={config} />;
};

export const Route = createFileRoute('/table')({
  component: RouteComponent
});
